ALTER TABLE orders 
ALTER COLUMN order_ID SET NOT NULL,
ALTER COLUMN A_ID SET NOT NULL,
ALTER COLUMN Buyers_ID SET NOT NULL,
ALTER COLUMN Product_ID SET NOT NULL,
ALTER COLUMN Order_Date SET NOT NULL,
ALTER COLUMN Total SET NOT null;