ALTER TABLE sales  
ALTER COLUMN A_ID SET NOT null,
ALTER COLUMN product_ID SET NOT NULL,
ALTER COLUMN Sales_ID SET NOT NULL,
ALTER COLUMN Sales_total SET NOT NULL,
ALTER COLUMN Sales_date SET NOT null;